### PR TITLE
Revert "Update get-dependencies.bat to Daml Finance 1.0.0 (#94)"

### PR DESCRIPTION
**Pull request by matevarga-da**
Reverts digital-asset/daml-finance-app#94 Figured out while testing that I messed up two of the entries.

### CODE REVIEW

**Comment by GeorgSchneider** [comment]
I didn't notice - which ones are wrong? Let's just fix those then

**Comment by matevarga-da** [comment]
Sorry it took me a while to run the batch script on linux.
line 33-34 shoule be
```
call :get_dependency daml-finance-interface-types-common        Daml.Finance.Interface.Types.Common       1.0.0
call :get_dependency daml-finance-interface-types-date          Daml.Finance.Interface.Types.Date         1.0.0
```

instead of
`call :get_dependency daml-finance-interface-types               Daml.Finance.Interface.Types.Common       1.0.0
call :get_dependency daml-finance-interface-types              Daml.Finance.Interface.Types.Date         1.0.0`

**Comment by GeorgSchneider** [comment]
ah right. can you just change this PR to fix it, rather than reverting?

**Comment by matevarga-da** [comment]
Sure

**Pull request merged**
